version: '3'
services:
  neo4j-host:
    image: neo4j:3.5.12
    environment:
      - NEO4J_AUTH=neo4j/tweet
      - NEO4J_dbms_connector_bolt_tls__level=OPTIONAL
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    command: neo4j
  mongodb-host:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    command: mongod
  tweetalyzer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - neo4j-host
      - mongodb-host
    restart: on-failure
    command: ["/bin/sh", "-c", "exec java -Dspring.profiles.active=docker -jar /opt/tweetalyzer-1.jar"]
